### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by pavlosamonin** [litecoin-project/insight-lite-api#17]
While running command
litecore-node install insight-lite-api
got an error
/usr/local/lib/node_modules/litecore-node/lib/cli/main.js:75
        throw new Error('Could not find configuration, see `litecore-node create --help`');
        ^

Error: Could not find configuration, see `litecore-node create --help`
    at Command.<anonymous> (/usr/local/lib/node_modules/litecore-node/lib/cli/main.js:75:15)
    at Command.listener (/usr/local/lib/node_modules/litecore-node/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:87:13)
    at Command.emit (events.js:172:7)
    at Command.parseArgs (/usr/local/lib/node_modules/litecore-node/node_modules/commander/index.js:651:12)
    at Command.parse (/usr/local/lib/node_modules/litecore-node/node_modules/commander/index.js:474:21)
    at Object.main (/usr/local/lib/node_modules/litecore-node/lib/cli/main.js:143:11)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/litecore-node/lib/cli/bitcore.js:31:16)
    at Liftoff.execute (/usr/local/lib/node_modules/litecore-node/node_modules/liftoff/index.js:203:12)
    at module.exports (/usr/local/lib/node_modules/litecore-node/node_modules/liftoff/node_modules/flagged-respawn/index.js:51:3)

Any ideas?

**Comment by losh11** [comment]
Follow the instructions here and replace `bitcore` with `litecore` and
`insight-api` with `insight-lite-api` and `insight-ui` with
`insight-lite-ui`.

https://bitcore.io/guides/full-node

**Comment by pavlosamonin** [comment]
I followed these instructions 
npm install -g litecore-node@latest
litecore-node create mynode
cd mynode
litecore-node install insight-lite-api
litecore-node start
that you wrote in your repo

Also I tried your issue 

RUN apt-get install -y libzmq3-dev build-essential python
RUN npm install zeromq --zmq-external
RUN npm install -g litecore
RUN litecore install insight-lite-api
RUN litecored

and got the same error

/usr/local/lib/node_modules/litecore/node_modules/litecore-node/lib/cli/main.js:75
        throw new Error('Could not find configuration, see `litecore-node create --help`');
        ^

Error: Could not find configuration, see `litecore-node create --help`
    at Command.<anonymous> (/usr/local/lib/node_modules/litecore/node_modules/litecore-node/lib/cli/main.js:75:15)
    at Command.listener (/usr/local/lib/node_modules/litecore/node_modules/litecore-node/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:87:13)
    at Command.emit (events.js:172:7)
    at Command.parseArgs (/usr/local/lib/node_modules/litecore/node_modules/litecore-node/node_modules/commander/index.js:651:12)
    at Command.parse (/usr/local/lib/node_modules/litecore/node_modules/litecore-node/node_modules/commander/index.js:474:21)
    at Object.main (/usr/local/lib/node_modules/litecore/node_modules/litecore-node/lib/cli/main.js:143:11)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/litecore/node_modules/litecore-node/lib/cli/bitcore.js:31:16)
    at Liftoff.execute (/usr/local/lib/node_modules/litecore/node_modules/litecore-node/node_modules/liftoff/index.js:203:12)
    at module.exports (/usr/local/lib/node_modules/litecore/node_modules/litecore-node/node_modules/liftoff/node_modules/flagged-respawn/index.js:51:3)

**Comment by losh11** [comment]
`litecore` not `litecore-node`. Again, please read the instructions carefully: https://bitcore.io/guides/full-node

**Comment by pavlosamonin** [comment]
Please, look at your Readme.md Getting Started section!
You wrote litecore-node everywhere.
